# Generated by Django 3.1.4 on 2020-12-28 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbonapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_image',
            name='caption',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
